# Generated by Django 3.2.9 on 2021-11-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20211117_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='loan',
        ),
    ]
